### ISSUE TITLE
docker-compose zookeeper cluster not starting from plugin but starting from normal compose

### ISSUE THREAD

**Issue by KasperJanssens** [fabric8io/docker-maven-plugin#1104]
I have a docker compose file like this
```
version: '2.4'
services:

  zookeeper1:
    build: zookeeper
    image: zookeeper1
    command: ["1", "zookeeper1:2888:3888", "2", "zookeeper2:2889:3889", "3", "zookeeper2:2890:3890"]
    ports:
      - "2181:2181"
  zookeeper2:
    build: zookeeper
    image: zookeeper2
    command: ["2", "zookeeper2:2889:3889", "1", "zookeeper1:2888:3888", "3" , "zookeeper2:2890:3890"]
    ports:
      - "2182:2181"
  zookeeper3:
    build: zookeeper
    image: zookeeper3
    command: ["3", "zookeeper2:2890:3890", "2","zookeeper2:2889:3889", "1", "zookeeper1:2888:3888"]
    ports:
      - "2183:2181"
```
When I run this docker-compose file with docker-compose, this zookeeper cluster works. When I do it from the docker-maven-plugin the zookeepers do not find each other (as in, zookeeper1 reports zookeeper2 is an unknown host).

is this expected behaviour with the network part of docker-compose not being supported yet according to the documentation? All dockers are reported as started but their services do not seem to find each other.

The maven config is like this
```
                <configuration>
                    <images>
                        <image>
                            <name>name_goes_here</name>
                            <alias>alias_goes_here</alias>
                            <external>
                                <type>compose</type>
                                <basedir>folder_goes_here</basedir>
                                <composeFile>docker-compose.yml</composeFile>
                            </external>
                        </image>
                    </images>
                </configuration>
```
docker compose plugin 0.27.1, maven 3.5.4 openjdk 10.0.2, ubuntu 18.04 docker 17.06.2, docker-compose 1.22.0.
