### ISSUE TITLE
Log file not working with compose

### ISSUE THREAD

**Issue by ben-gineer** [fabric8io/docker-maven-plugin#1141]
### Description
I'm unable to persist any logs when using the compose form of configuration.

Here's my compose:
```
version: "2"
services:
  mysql:
    image: myproduct.com/mysql:${datalayerversion}
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
xo-management-service:
    image: myproduct.com/xo-management-service:${projectversion}
    ports:
      - "8093:8093"
    links:
      - mysql
    environment:
      - loglevel=debug
      - dbtype=MYSQL
      - dbclass=com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      - dbhost=mysql
      - dbname=cd_broker_discovery_db
      - dbuser=root
      - dbpassword=1234
      - dbport=3306
      - service=xo-management-service
    container_name: "xo-management-service"
```

Here's my pom:
```
<plugin>
                        <groupId>io.fabric8</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>start-test-containers</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>stop</goal>
                                    <goal>start</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>stop-test-containers</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>stop</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <logStdout>true</logStdout>
                            <logDate>default</logDate>
                            <verbose>true</verbose>
                            <images>
                                <image>
                                    <alias>xo-management-service</alias>
                                    <external>
                                        <ignoreBuild>true</ignoreBuild>
                                        <type>compose</type>
                                    </external>
                                    <run>
                                        <wait>
                                            <http>
                                                <url>http://${docker.host.address}:8093/health</url>
                                                <method>GET</method>
                                                <status>200</status>
                                            </http>
                                            <time>180000</time>
                                        </wait>
                                        <log>
                                            <enabled>true</enabled>
                                            <color>yellow</color>
                                            <file>${project.build.directory}/container.log</file>
                                            <driver>
                                                <name>json-file</name>
                                            </driver>
                                        </log>
                                    </run>
                                </image>
                            </images>
                            <imagePullPolicy>IfNotPresent</imagePullPolicy>
                        </configuration>
                    </plugin>
```

I've tried various combinations of the log file and driver options, but I'm not able to see any generated log files. The console output gets generated correctly.

Should the log setting work with compose files?

### Info

* d-m-p version : 0.26.1
* Maven version (`mvn -v`) : 3.6.0
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T19:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.1", arch: "x86_64", family: "mac"
```
* Docker version : Engine: 18.09.0
