### ISSUE TITLE
Cannot start containers defined by docker-compose without local kubernetes cluster

### ISSUE THREAD

**Issue by cambiph** [fabric8io/docker-maven-plugin#1149]
### Description

I am using the fabric8 maven plugin to start a selenium grid and a postgres database. All services are defined in a docker-compose file. During the `generate-resources` phase, the containers are `start`ed. However, the containers fail to start and throw an `UnknownHostException` stating:

```[ERROR] F8: Could not connect to kubernetes cluster!
[ERROR] F8: Have you started a local cluster via `mvn fabric8:cluster-start` or connected to a remote cluster via `kubectl`?
[INFO] F8: For more help see: http://fabric8.io/guide/getStarted/
[ERROR] F8: Connection error: %s: java.net.UnknownHostException: kubernetes.default.svc
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.42:start (start) on project ***: Could not connect to kubernetes cluster. Have you started a cluster via `mvn fabric8:cluster-start` or connected to a remote cluster via `kubectl`? Error: java.net.UnknownHostException: kubernetes.default.svc: An error has occurred. Unknown host kubernetes.default.svc -> [Help 1]
```
### Info

* f-m-p version : 3.5.42
* Maven version (`mvn -v`) : 3.5.4

`pom.xml`
```
<plugin>
    <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
</plugin>
<plugin>
    <groupId>io.fabric8</groupId>
    <artifactId>fabric8-maven-plugin</artifactId>
    <version>3.5.42</version>
        <configuration>
            <registry>${DOCKER_REGISTRY}</registry>
            <composeFile>docker-compose-hub.yml</composeFile>
        </configuration>

    <executions>
        <execution>
            <id>start</id>
            <phase>generate-resources</phase>
            <goals>
                <goal>start</goal>
            </goals>
        </execution>
        <execution>
            <id>stop</id>
            <phase>post-integration-test</phase>
            <goals>
                <goal>stop</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

`docker-compose-hub.yml`

```
# https://github.com/SeleniumHQ/docker-selenium
version: "3"
services:
  selenium-hub:
    image: ${DOCKER_REGISTRY}selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - 4444:4444
    environment:
      - NODE_MAX_SESSION=5
      - GRID_DEBUG=true
  selenium-chrome:
    image: ${DOCKER_REGISTRY}selenium/node-chrome-debug:3.141.59
    container_name: chrome
    ports:
      - 5900:5900
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SHM-SIZE=2g
      - GRID_DEBUG=true
  selenium-firefox:
    image: ${DOCKER_REGISTRY}selenium/node-firefox-debug:3.141.59
    container_name: firefox
    ports:
      - 5901:5900
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SHM-SIZE=2g
  db:
    image: ${DOCKER_REGISTRY}postgres:9.6.11
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=****
      - POSTGRES_USER=build
      - POSTGRES_PASSWORD=build
```
* Kubernetes / OpenShift setup and version : none
* If it's a bug, how to reproduce : run above config with specified docker-compose YAML
* If it's a feature request, what is your use case : none
* Sample project : config above can be pasted in a barebones maven project
