### ISSUE TITLE
External Compose and Wait seems not working

### ISSUE THREAD

**Issue by grrolland** [fabric8io/docker-maven-plugin#1792]
### Description
When using external  docker compose as : 

```
version: "2.0"
services:
  minio:
    image: quay.io/minio/minio
    restart: always
    environment:
      - MINIO_ROOT_USER=xxxxx
      - MINIO_ROOT_PASSWORD=xxxxx
    ports:
      - 19000:9000
      - 19001:9001
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    image: quay.io/minio/mc
    depends_on:
      - minio
    volumes:
      - ./files:/data
    links:
      - "minio:minio"
    entrypoint: "/bin/sh /data/init.sh"
  mc-end:
      image: quay.io/minio/mc
      entrypoint: "/bin/sh echo"
      depends_on:
          mc:
              condition: service_completed_successfully
```

And configuration as : 

```
 <configuration>
    <images>
        <image>
            <alias>test-env</alias>
            <name>test-env</name>
            <external>
                <type>compose</type>
                <basedir>test-env</basedir>
                <composeFile>docker-compose.yml</composeFile>
            </external>
            <run>
                <wait>
                    <time>3600000</time>
                </wait>
            </run>
        </image>
    </images>
    <showLogs>true</showLogs>
</configuration>
```

Here I expect : 
- start the minio image
- start the mc client with init script executed
- wait for mc image completed wit mc-end

When the init.sh from the mc container run for a long time (more than 10s), I have this error : 

```
DOCKER> I/O Error [[quay.io/minio/mc:latest] "mc": Timeout after 10287 ms while waiting on exit code 0]
```

The wait configuration seems to ne be applied

### Info

* docker-maven-plugin version : 0.44.0
* Maven version (`mvn -v`) : Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
* Docker version : Docker version 25.0.3, build 4debf41
