### ISSUE TITLE
Volume support for docker-compose files

### ISSUE THREAD

**Issue by rhuss** [fabric8io/docker-maven-plugin#671]
### Description

Now that we have volume support thanks to #664 and #669 support for docker-compose top-level volumes can be added.

**Comment by rohanKanojia** [comment]
@rhuss : Hey, Does this feature still look valid to you? Can I pick it up?

**Comment by rhuss** [comment]
@rohanKanojia Yes, this is still valid. Feel free to jump on it. 

Thanks !

**Comment by rohanKanojia** [comment]
Hi @rhuss ,

Could you please put some light on what support are we talking about here? I think there is already support for volumes in docker-compose(I might be missing something here). Here are the steps I did:

1. Modified `samples/docker-compose/src/main/docker/docker-compose.yml` to add volumes:
```
     labels:
       "dmp.type": "example"
       "dmp.value": "100$$"
+    volumes:
+      - /var/local/mysql:/mysql
   tomcat:
     image: "fabric8/tomcat-7:latest"
     ports:
```

2. I built the image using `docker:build`

3. I ran the container using `docker:start` and did these:
```
~/work/repos/fabric8-maven-plugin : $ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                        NAMES
f85417e96abd        fabric8/tomcat-7:latest   "/bin/sh -c /opt/t..."   5 seconds ago       Up 4 seconds        8778/tcp, 0.0.0.0:8080->8080/tcp, 9779/tcp   friendly_noether
~/work/repos/fabric8-maven-plugin : $ docker exec -it f85417e96abd /bin/bash
[jboss@f85417e96abd ~]$ 
[jboss@f85417e96abd ~]$ 
[jboss@f85417e96abd ~]$ ls /mysql
data  ib_logfile0  ib_logfile1  ibdata1  items  mysql  performance_schema
[jboss@f85417e96abd ~]$ 
```
