### ISSUE TITLE
Naming containers

### ISSUE THREAD

**Issue by jssbbonilla** [fabric8io/docker-maven-plugin#751]
Is there a way to name container using an external docker-compose file?
I want to start two container in docker-compose (it works out of maven):

 version: '2'

```
services:
    marcons:
        container_name: 'uesmariadb:latest'
        image: 'ownmariadb'
        build: ./mariadb/.
        environment: 
        - 'MYSQL_ROOT_PASSWORD=12345'
        ports:
        - '3306:3306'
    paycons: 
        container_name: 'uespayara:latest'
        image: 'ownpayara'
        build: ./payara/.   
        ports:
        - "8080:8080"
        - "4848:4848"
        entrypoint:
        - "./wait-for-mariadb.sh"
        - "uesmariadb:3306"
        - "-t"
        - "60"
        - "--"
        - "bin/asadmin"
        - "start-domain"
        - "-v"
```

And i need to use these names for each container , but it doesn't work.... 
my POM:
```
<build>
       <plugins>
       <plugin>
           <groupId>io.fabric8</groupId>
           <artifactId>docker-maven-plugin</artifactId>
           <extensions>true</extensions>
           <configuration>
               <images>
                   <image>
                       <external>
                           <type>compose</type>
                           <basedir>../../../docker/</basedir>
                           <composeFile>docker-compose.yml</composeFile>
                       </external>
                   </image>
               </images>
           </configuration>
           <executions>
               <execution>
                   <id>start</id>
                   <phase>pre-integration-test</phase>
                   <goals>
                       <!-- "build" should be used to create the images with the
                       artifact -->
                       <goal>build</goal>
                       <goal>start</goal>
                   </goals>
               </execution>
           </executions>
       </plugin>
   </plugins>
   </build>
```

In console:

[INFO] --- docker-maven-plugin:0.20.1:start (start) @ some ---
[INFO] DOCKER> [ownmariadb:latest] "uesmariadb:latest": Start container c1bf05c2ab2c
[INFO] DOCKER> [ownpayara:latest] "uespayara:latest": Start container bdd4e00a2a55
 but the names are random (docker ps).
can you help solving that?
