### ISSUE TITLE
Question - How can I get the port into a Maven property when using Docker compose?

### ISSUE THREAD

**Issue by rrrrrrrrramba** [fabric8io/docker-maven-plugin#893]
This is a question, not an issue.

I am trying to figure out how to initialize the dynamic port of a Docker Tomcat container which has been started by a Docker compose script from the docker-maven-plugin, but I am hitting a wall.

I have a regular **docker-compose.yml**:

```
services:
  tomcat:
    image: "tomcat:8.5"
    ports:
    - tomcat-port:8080
```

As you see, I am using `tomcat-port:8080`. Is this the way to get the chosen port into a Maven property, so I can use it by `${tomcat-port}` afterwards?

Thank you very much.
