### ISSUE TITLE
external compose fails

### ISSUE THREAD

**Issue by nicolasduminil** [fabric8io/docker-maven-plugin#895]
### Description
Using external compose with the docker-compose.yml file below:

```yml
version: "2"
services:
  ....
  db:
    image: oracle/database:11.2.0.2-xe
    container_name: oraxe
    shm_size: 1g
    ports:
      - 1521:1521
      - 80:8080
```

raises the following exception:

```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.22.1:start (default-cli) on project customer-management-ear: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.22.1:start failed: For input string: "1g" 
```

Obviously it has to do with the line "shm_size: 1g". Running the same file with the command:

docker-compose up -d

works as expected. What could be the problem here ?
### Info

* d-m-p version : 0.22.1
* Maven version (`mvn -v`) : 3.3.9

* Docker version : 17.09.ce
